_wandb:
    value:
        cli_version: 0.23.1
        e:
            wy6m5p200kml7iiwfquu64r8icblezxn:
                args:
                    - --policy_type=flow
                    - --wandb_project=flow_updateimp
                    - --num_epochs=1000
                    - --flow_num_steps=15
                codePath: src/hw1_imitation/train.py
                codePathLocal: src/hw1_imitation/train.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "63090503680"
                        used: "38144593920"
                email: alex_zhao@berkeley.edu
                executable: /scratch/users/alex_zhao/hw1/.venv/bin/python3
                gpu: NVIDIA GeForce RTX 2080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-649bc25a-1e27-b867-41b3-16140fca0063
                host: shadowfax
                memory:
                    total: "134784618496"
                os: Linux-6.8.0-56-generic-x86_64-with-glibc2.39
                program: /scratch/users/alex_zhao/hw1/src/hw1_imitation/train.py
                python: CPython 3.11.14
                root: /scratch/users/alex_zhao/hw1
                slurm:
                    account: site
                    cluster_name: screms
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "2"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: site
                    job_cpus_per_node: "1"
                    job_end_time: "1770872128"
                    job_gid: "22011"
                    job_id: "2888641"
                    job_name: interactive
                    job_nodelist: shadowfax
                    job_num_nodes: "1"
                    job_partition: jsteinhardt
                    job_qos: normal
                    job_start_time: "1770785728"
                    job_uid: "3636"
                    job_user: alex_zhao
                    jobid: "2888641"
                    launch_node_ipaddr: 128.32.135.47
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: shadowfax
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "19"
                    procid: "0"
                    pty_port: "42623"
                    pty_win_col: "133"
                    pty_win_row: "10"
                    script_context: prolog_task
                    srun_comm_host: 128.32.135.47
                    srun_comm_port: "35245"
                    step_gpus: "2"
                    step_id: "0"
                    step_launcher_port: "35245"
                    step_nodelist: shadowfax
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 12481-12482
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /scratch/users/alex_zhao/hw1
                    submit_host: gandalf
                    task_pid: "1412481"
                    tasks_per_node: "1"
                    topology_addr: shadowfax
                    topology_addr_pattern: node
                    umask: "0022"
                    working_cluster: screms:128.32.135.2:6817:9984:109
                startedAt: "2026-02-11T09:39:05.095335Z"
                writerId: wy6m5p200kml7iiwfquu64r8icblezxn
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 128
chunk_size:
    value: 8
data_dir:
    value: data
eval_interval:
    value: 10000
exp_name:
    value: null
flow_num_steps:
    value: 15
hidden_dims:
    value:
        - 256
        - 256
        - 256
log_interval:
    value: 100
lr:
    value: 0.0003
num_epochs:
    value: 1000
num_video_episodes:
    value: 5
policy_type:
    value: flow
seed:
    value: 42
video_size:
    value:
        - 256
        - 256
wandb_project:
    value: flow_updateimp
weight_decay:
    value: 0
